### ISSUE TITLE
Subscribe Feed (Atom) & OPML format

### ISSUE THREAD

**Issue by VoidSec** [moonmoon/moonmoon#63]
Installed and added some feeds, when someone try to subscribe to moonmoon in both format, atom and opml, instead a subscribe default action a page with all feeds code is opening...
Look here for more info: http://rss.voidsec.com/ (try to click Feed ATOM)

**Comment by nashe** [comment]
Landed in https://github.com/moonmoon/moonmoon/commit/b8022f37a1a2aef5284a217134a0c5413701a129. The MIME type `text/xml` is not the correct one but all the popular feeds are announcing it in their feeds, so we'll make the same.
The related Firefox _wontfix_ bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=155730.
