### ISSUE TITLE
Transfer ownership of moonmoon to the community

### ISSUE THREAD

**Issue by mauricesvay** [moonmoon/moonmoon#89]
I'm creating this issue to track the transfer of moonmoon to the community

- [x] Create a github organization to own the repository
- [x] Host moonmoon.org on github pages

**Comment by mauricesvay** [comment]
I've contacted github to recover the "moonmoon" username to create an organization. If it's not possible, we'll have to settle with a different username, like moonmoonorg or similar.

For the website, I can sponsor the domain name. I still need to properly set up the CNAME.

**Comment by nashe** [comment]
👍 

Using a platform like [Gratipay](https://github.com/gratipay/gratipay.com/) could be a good way to centralize such donations from the community, it could be interesting to add moonmoon on it once a stable release of the 9.0 will be out.

**Comment by mauricesvay** [comment]
@nashe I've created the moonmoon organization. I think it would be best to transfer the repository to the organization, but it means that the URL will change. Is that ok for you?

**Comment by nashe** [comment]
It seems (as per https://github.com/blog/1508-repository-redirects-are-here) that any access to https://github.com/mauricesvay/moonmoon/ will redirect to the new repository. OK for me!

**Comment by mauricesvay** [comment]
I've managed to recover the moonmoon username to create the organization. The repository has been transferred to the organization.

The website http://moonmoon.org/ is now properly served by github pages. The domain is currently registered at bookmyname.com, and using alwaysdata.com DNS servers.

We should be all set now. I'm closing the issue :)
