### ISSUE TITLE
install.php file : is the language in spanish possible ?

### ISSUE THREAD

**Issue by Emmafrs** [moonmoon/moonmoon#90]
Hello, i'm french and not spanish, but i saw somewhere (here : https://github.com/mauricesvay/moonmoon/commit/b37de7f1afab72e266a1d25b6635f20e8b025f88) the moonmoon had a translation in spainish. 

We can choose our language in the install.php file, english or french, is it possible to add the spanish language ?

**Comment by nashe** [comment]
Nice catch!

What needs to be done:
- [ ] Add the `es` locale in [install.php](https://github.com/mauricesvay/moonmoon/blob/master/install.php#L165)
- [ ] Ensure that a locale exists before writing it to the configuration file (does `app/l10n/$locale.lang` exist?)

Do you want to try to do it or I'll assign this issue to myself?

**Comment by Emmafrs** [comment]
I don't exactly understand what you say, but i test it : there is already the spain langage file in the l10n file. 

What we just have to do to add the spanish langage is to add a code in the install.php file (line 163 and ```
after) : 
               <p class="field">
                    <label for="locale">Language:</label>
                    <select name="locale" id="locale">
                        <option selected="selected" value="en">English</option>
                        <option value="fr">Français</option>
			<option value="es">espanol</option>
                    </select>
                </p>
```
and that's all, it's working, i just did the install in choosing the spanish langage.

**Comment by nashe** [comment]
I was just trying to tell that we should make sure that the user selects a valid locale before writing it in the configuration (see https://github.com/moonmoon/moonmoon/commit/28a1dd7b5c068360968dfb648fe1b620e8902645#diff-3b7de2cf163f18aa521c050bb543084fR16).

**Comment by Emmafrs** [comment]
Ok, well done :)
