### ISSUE TITLE
install.php : not totally clean ? 

### ISSUE THREAD

**Issue by Emmafrs** [moonmoon/moonmoon#91]
Hello, 
I just saw there was still 3 "`dirname(__FILE__)`" instead of "`__DIR__`" in the install.php file (line 12, 13 and 62). I don't know if it's ok or not. 

And for style, line 33 and 36, there is 2 "`__DIR__`" without space after (yes i chipote ;)).

**Comment by nashe** [comment]
Yes, it can be improved! `dirname(__FILE__)` is an artifact of the PHP 5.3 support, it can safely be replaced by `__DIR__` now :-)
