### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Emmafrs** [moonmoon/moonmoon#94]
Hello, 
There was an issue about it : #59 

Is it a work in progress or an abandonned idea ?

**Comment by mauricesvay** [comment]
Nothing has been done about it. Having a responsive default theme would be nice.

**Comment by JonathanMM** [comment]
I put some little modification to change the default style a little more responsive. I use it (with a image in background) on the planet of my organisation: https://planet.atnl.fr/
