### ISSUE TITLE
A little little bug in the Admin page

### ISSUE THREAD

**Issue by Emmafrs** [moonmoon/moonmoon#95]
Hello, 

Just find something strange : 
in the admin page, I add a feed (or link of the website). This feed (or link of the website) find automatically the title of the website. 
IF the title has an accent (é, è, ë or wathever) and if I do nothig but go and refresh the main page, oh oh oh, the title will be wrong in the sidebar (with a '`&eacute;`' instead of an 'é' for exemple). 

But don't panic, I just have to go to the admin page, click on the "save changes" button, and everything's allright.

Sometimes the title has an accent and everything's fine without clicking on the "save changes" button. It's a problem with how the people code their feeds I think. 

Exemples : 
- http://feeds.feedburner.com/LaperoDuCaptain?format=xml  : title will be wrong in the main page without clicking on the "save changes" button.
- https://www.alsacreations.com/rss/actualites.xml : no problem.

**Comment by nashe** [comment]
It should be fixed with https://github.com/moonmoon/moonmoon/commit/c0b51f5f9621c6063af8677637ea120e9bab8ab5, can you confirm? Thanks!

**Comment by Emmafrs** [comment]
Yes, yes, I can confirm it ! (à lire sur le ton de l'assistante du magicien face au public ;), tout est nickel, merci).
